### ISSUE TITLE
faster cost calculation

### ISSUE THREAD

**Issue by fbaumdicker** [k-burger/tangles_in_pop_gen#1]
I think this pairwise computation can be done outside of the loop, such that we do not compute the pairwise differences over and over again. Instead we could compute the pairwise differences once for all pairs and then only lookup the necessary comparisons when comparing two parts of a cut.

This should really speed up the cost computation.

https://github.com/k-burger/tangles_in_pop_gen/blob/a7ee2a5fbb57bab9da8c0944dcca36b93c942074/src/cost_functions.py#L277

Do you agree @sklepper ?

**Comment by k-burger** [comment]
This has been addressed, even if we now use a cost function specific to population genetics instead of the mean Manhattan distance mentioned here.
